_wandb:
    value:
        cli_version: 0.21.0
        e:
            jm9ovd3o588qukshzw0nk559ru9gmtcp:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "696315113472"
                        used: "461569949696"
                email: albert.bastl@protonmail.com
                executable: /bin/python3
                git:
                    commit: 57f6ebae9ee26d10297093ec5aa56fd6431a8ab7
                    remote: https://mrs.fel.cvut.cz/gitlab/bastlalb/prompt-guided-object-localizer.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-e32788e6-a31a-2b33-723f-de0dd75774d4
                host: pop-os
                memory:
                    total: "33332785152"
                os: Linux-6.12.10-76061203-generic-x86_64-with-glibc2.35
                program: /home/albertbastl/Documents/MRS/prompt-guided-object-localizer/train.py
                python: CPython 3.10.12
                root: /home/albertbastl/Documents/MRS/prompt-guided-object-localizer
                startedAt: "2025-07-29T13:42:47.216269Z"
                writerId: jm9ovd3o588qukshzw0nk559ru9gmtcp
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 105
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.21.0
            "6": 4.53.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 256
checkpoint_every:
    value: 500
embed_dim:
    value: 768
epochs:
    value: 10
grid_size:
    value: 14
learning_rate:
    value: 6.9e-05
log_images_every:
    value: 2
model_id:
    value: google/siglip2-base-patch16-224
num_heads:
    value: 2
num_layers:
    value: 4
